### ISSUE TITLE
[Question] Deprecate Python 2.7 and 3.5 support?

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/tld#102]
@Yomguithereal:

This is just a question for now. Do you still use Python 2.7 and 3.5 environments?

**Comment by Yomguithereal** [comment]
Against my will yes I still use python 2.7 environments. But when I use python 3 I seldom go less than 3.6. If this becomes a burden to maintain the v2 for you I can also pin the dep on `tld` on my end so that you can advance without hurdle.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

No need to pin just yet. :) I'll support it as long as you use it. Closing this for now. Will ping again in a year or so. :) Thanks!

**Comment by Yomguithereal** [comment]
> I'll support it as long as you use it.

Maybe you don't want to do that :). For the record, my lab uses your library through another one of mine [here](https://github.com/medialab/ural) to be used in a web crawler called [Hyphe](https://hyphe.medialab.sciences-po.fr/), which was started ten years ago and was naturally developped in python2. But since the codebase is pretty large and uses old async schemes through `twisted` we never had the fundings to be able to port it to python3. So we maintain it in python2, which is quite a pain I must admit :)

My point being at one point you might want to ignore this and drop py2 support and we will ensure it is not an issue for us to do so.

**Comment by barseghyanartur** [comment]
@Yomguithereal:

Just refreshing. Do you still use Python2.7?
